services:
  - type: web
    name: lic-advisor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_dashboard.py --server.port $PORT --server.address 0.0.0.0 --browser.gatherUsageStats false
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 