[global]
# Global configuration for the Streamlit app

# Development mode
developmentMode = false

# Show error details
showErrorDetails = true

# Data frame serialization
dataFrameSerialization = "legacy"

[server]
# Server configuration

# Port to run the app on
port = 8501

# Enable CORS
enableCORS = true

# Enable XSS protection
enableXsrfProtection = true

# Max upload size (200MB)
maxUploadSize = 200

# Max message size (200MB)
maxMessageSize = 200

# Enable websocket compression
enableWebsocketCompression = true

# Headless mode
headless = false

# Run on save
runOnSave = false

# Allow run on save
allowRunOnSave = false

# File watcher type
fileWatcherType = "auto"

# Cookie secret (for session management)
cookieSecret = "lic_dashboard_secret_key_2024"

[browser]
# Browser configuration

# Gather usage stats
gatherUsageStats = false

# Server address
serverAddress = "localhost"

# Server port
serverPort = 8501

[theme]
# Theme configuration

# Primary color (LIC Orange)
primaryColor = "#FF6B35"

# Background color
backgroundColor = "#FFFFFF"

# Secondary background color
secondaryBackgroundColor = "#F0F2F6"

# Text color
textColor = "#262730"

# Font family
font = "sans serif"

[client]
# Client configuration

# Show error details
showErrorDetails = true

# Toolbar mode
toolbarMode = "auto"

[runner]
# Runner configuration

# Magic enabled
magicEnabled = true

# Install tracer
installTracer = false

# Fix matplotlib
fixMatplotlib = true

# Post script GC
postScriptGC = true

# Fast reruns
fastReruns = true

[logger]
# Logger configuration

# Log level
level = "info"

# Message format
messageFormat = "%(asctime)s %(levelname) -7s %(name)s: %(message)s"

[deprecation]
# Deprecation warnings

# Show Pyplot global use
showPyplotGlobalUse = false
